### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by oOtroyOo** [ProteusVR/SteamVR_Template#10]
I cant build this project to WindowsNoEditor. My  UE4 Version is 4.12 
I created an empty project ,and copy VRGripMotionControllerPlugin to the project and enabled it.
Then I tried to build this project as WindowsNoEditor. And ..BOOM..
I think this issue  might coused by the VRGripMotionControllerPlugin.
How can i fix it ?

this is Editor logs :
`
MainFrameActions: 打包 (Windows (64位)): Running AutomationTool...
MainFrameActions: 打包 (Windows (64位)): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject=D:/Documents/Unreal Projects/test/test.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=D:/Documents/Unreal Projects/test/test.uproject -cook -stage -archive -archivedirectory=E:/Desktop/Builds -package -clientconfig=Developm
ent -ue4exe=UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -CrashReporter -utf8output
MainFrameActions: 打包 (Windows (64位)): Automation.Process: Setting up command environment.
MainFrameActions: 打包 (Windows (64位)): BuildCookRun.SetupParams: Setting up ProjectParams for D:\Documents\Unreal Projects\test\test.uproject
MainFrameActions: 打包 (Windows (64位)): Project.Build: ********** BUILD COMMAND STARTED **********
MainFrameActions: 打包 (Windows (64位)): CommandUtils.Run: Run: D:\Program Files\Epic Games\4.12\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Game Win64 Development   -remoteini="D:\Documents\Unreal Projects\test" -noxge -generatemanifest -NoHotReloadFromIDE
MainFrameActions: 打包 (Windows (64位)): UnrealBuildTool: ERROR: No modules found to build. All requested binaries were already part of the installed engine data.
MainFrameActions: 打包 (Windows (64位)): CommandUtils.Run: Run: Took 1.35s to run UnrealBuildTool.exe, ExitCode=5
MainFrameActions: 打包 (Windows (64位)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.AutomationException: Command failed (Result:5): D:\Program Files\Epic Games\4.12\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Game Win64 Development   -remoteini="D:\Documents\Unreal Projects\test" -noxge -generatemanifest -NoHotReloadFromIDE.
 See logfile for details: 'UnrealBuildTool-2016.07.01-16.16.29.txt' 
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary
`2 InTargetToManifest)
MainFrameActions: 打包 (Windows (64位)):    在 Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
MainFrameActions: 打包 (Windows (64位)):    在 BuildCookRun.DoBuildCookRun(ProjectParams Params)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.BuildCommand.Execute()
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.Automation.Process(String[] CommandLine)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.Program.MainProc(Object Param)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
MainFrameActions: 打包 (Windows (64位)):    在 AutomationTool.Program.Main()
MainFrameActions: 打包 (Windows (64位)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
MainFrameActions: 打包 (Windows (64位)): Domain_ProcessExit
MainFrameActions: 打包 (Windows (64位)): copying UAT log files...
MainFrameActions: 打包 (Windows (64位)): BUILD FAILED
PackagingResults:Error: 错误 Unknown Error
`

**Comment by ProteusVR** [comment]
Be sure to download the last version of the plugin from https://bitbucket.org/mordentral/ue4-vr-grippable-motion-controller-plugin/downloads . For the rest, I'll release a new version 1.11 in 1-2 days with extensive docs everything should works flawlessly after that
